/**
 * Constants for every front end route in the application.
 */
export const SIGNIN = "/signin";
export const SIGNUP = "/signup";
export const FORGET_PASSWORD = "/forget-password";
// MUST MATCH THE ONE GENERATED BY SYMFONY:
export const RESET_PASSWORD = "/new-password/api/:password_token";
// MUST MATCH THE ONE GENERATED BY SYMFONY:
export const FIRST_LOGIN = "/first-login/api/:first_login_token";
export const PROFILE_MY_ACCOUNT = "/profile/my-account";
export const PROFILE_PASSWORD = "/profile/password";

export const DASHBOARD = "/dashboard";

export const USER_CRUD_LIST = "/backend/user";
export const USER_CRUD_NEW = "/backend/user/new";
export const USER_CRUD_EDIT = "/backend/user/:id/edit";

export const ACCOUNT_SETTINGS = "/account/settings";

export const MAIL_LIST_CRUD_LIST = "/lists";
export const MAIL_LIST_CRUD_NEW = "/lists/new";
export const MAIL_LIST_CRUD_EDIT = "/lists/:id/edit";
export const MAIL_LIST_CONTACTS = "/lists/:id/contacts";
export const MAIL_LIST_CONTACTS_NEW = "/lists/:id/contacts/new";
export const MAIL_LIST_CONTACTS_EDIT = "/lists/:id/contacts/:contactId/edit";
export const MAIL_LIST_CONTACTS_IMPORT = "/lists/:id/import";

export const CAMPAIGN_CRUD_LIST = "/campaigns";
export const CAMPAIGN_CRUD_NEW = "/campaigns/new";
export const CAMPAIGN_CRUD_EDIT = "/campaigns/:id/edit";
export const CAMPAIGN_STATS = "/campaigns/:id/stats";
