/**
 * Constants for every front end route in the application.
 */
export const SIGNIN = "/signin";
export const SIGNUP = "/signup";
export const FORGET_PASSWORD = "/forget-password";
// MUST MATCH THE ONE GENERATED BY SYMFONY:
export const RESET_PASSWORD = "/new-password/api/:password_token";
// MUST MATCH THE ONE GENERATED BY SYMFONY:
export const FIRST_LOGIN = "/first-login/api/:first_login_token";
export const PROFILE_MY_ACCOUNT = "/profile/my-account";
export const PROFILE_PASSWORD = "/profile/password";

export const DASHBOARD = "/dashboard";

export const USER_CRUD_LIST = "/backend/user";
export const USER_CRUD_NEW = "/backend/user/new";
export const USER_CRUD_EDIT = "/backend/user/:id/edit";

export const ACCOUNT_SETTINGS = "/account/settings";
